'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QuillProvider, Dashboard } from "@quillsql/react";

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <QuillProvider organizationId='2' publicKey='62cda15d7c9fcca7bc0a3689'>
            <>{children}</>
          </QuillProvider>
        </body>
      </html>
  )
}
